---
# This playbook ensures presence of the project with user for testing to be
# executed in

- hosts: os_infra
  tasks:

    - name: Create Project
      os_project:
        name: "{{ test_project_name }}"
        state: present
        description: "Project for executing tests"
      register: project

    - name: Create UserGroup
      os_group:
        state: present
        name: "apimon_test_group"
        description: "User group for the users in the apimon_test projects"

    - name: Create test user
      os_user:
        state: present
        name: "{{ test_user_name }}"
        password: "{{ test_user_password }}"
        default_project: "{{ test_project_name }}"
        domain: "{{ project.project.domain_id }}"
        description: "APImon test user"

    - name: Add test user to group
      script: "assign_group_role.py {{ test_project_name }} apimon_test_group" 
