---
# Enable certbot on the target machine to generate certificates
#


- import_playbook: flush_jumphost_key.yaml

- hosts: all
  become: true
  gather_facts: true
  vars: 
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}" 
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_create_if_missing: true
    certbot_create_method: standalone

  roles:
    - role: opentelekomcloud_infra.certbot
      when: hostvars[inventory_hostname].certbot_certs is defined
