version: '3'

services:
  executor:
    build: ./executor
    # image: executor
    volumes:
      - ./inventory/production/clouds.yaml:/etc/openstack/clouds.yaml:Z
    restart: always

  telegraf:
    ports:
      - "8125:8125/udp"
      - "9273:9273"
    image: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro,Z
    restart: always

  prometheus:
    ports:
      - 9090:9090
    depends_on:
      - telegraf
    image: prom/prometheus
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - prometheus_data:/prometheus:Z
    restart: always

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: always

  grafana:
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana:Z
      - ./configs/grafana/provisioning/:/etc/grafana/provisioning/:Z
    env_file:
      - ./configs/grafana/config.monitoring
    restart: always

volumes:
  prometheus_data:
  grafana_data:
  influxdb_data:
