---
# tasks file for roles/server_create_delete

- name: Create Server
  os_server:
    auto_ip: false
    availability_zone: "{{ availability_zone | default(omit) }}"
    name: "{{ server_fqdn }}"
    image: "{{ server_image }}"
    flavor: "{{ server_flavor }}"
    key_name: "{{ server_keypair_name }}"
    network: "{{ server_net }}"
    security_groups: "{{ security_group }}"
  register: server

- name: Attach FIP
  os_floating_ip:
    server: "{{ server_fqdn }}"

- name: get server info
  os_server_facts:
    server: "{{ server_fqdn }}"

- set_fact:
    server_ip: "{{ openstack_servers[0]['public_v4'] }}"

# Wait for the server to really start and become accessible
- name: Check SSH to the server
  wait_for:
    port: 22
    host: "{{ server_ip }}"
    timeout: 300

- name: Delete server
  os_server:
    state: absent
    name: "{{ server_fqdn }}"
    delete_fip: True
