---
# Inventory for executors
clouds_yaml_content: |
  metrics:
   statsd:
     host: telegraf
     port: 8125
   influxdb:
     host: telegraf
     port: 8186
     username: foobar
     password: barfoo
     measurement: openstack_api
  clouds:
    otc:
      auth:
        auth_url: https://iam.eu-de.otc.t-systems.com:443/v3
        project_name: {{ test_project_name }}
        user_domain_name: {{ test_domain_name }}
        username: {{ test_user_name }} 
        password: {{ test_user_password }}
      interface: public
      identity_api_version: 3 
