---
# Inventory variables for Grafana hosts
#

influxdb_image_tag: "1.7.6"
influxdb_ssl_cert_name: influxdb.pem
influxdb_ssl_cert_content: "{{ apimon_ssl_cert_content }}"
influxdb_ssl_key_name: influxdb.key
influxdb_ssl_key_content: "{{ apimon_ssl_key_content }}"
influxdb_hostname: localhost
influxdb_apimon_db_name: "{{ apimon_db_name }}"

