---
# Playbook to install Executor
#
# This playbook requires following variables
#
# executor_apimon_repo_url
# executor_apimon_repo_ref
# executor_apimon_repo_location
# clouds_yaml_content

- import_playbook: flush_jumphost_key.yaml

- name: Provision Executor
  hosts: executor
  serial: 1
  roles:
    - opentelekomcloud.server_common
    - opentelekomcloud_infra.apimon_executor
  tasks:
  tags: executor

