---
# This playbook creates two LoadBalancers, one for haproxy and other for influx
#

# 
- name: Create ELB
  hosts: os_infra
  tasks:
    - name: Find subnet
      os_subnets_facts:
        name: "{{ ( prefix + 'default-subnet') }}"
      register: subnets

    - set_fact:
        subnet_id: "{{ subnets.ansible_facts.openstack_subnets[0].id }}"
    
    - name: Create "{{ haproxy_lb_name }}" LB
      otc_loadbalancer:
        name: "{{ haproxy_lb_name }}"
        state: present
        vip_subnet: "{{ subnet_id }}"
        auto_public_ip: true
      register: haproxy
 
    - name: Create "{{ influxdb_lb_name }}" LB
      otc_loadbalancer:
        name: "{{ influxdb_lb_name }}"
        state: present
        vip_subnet: "{{ subnet_id }}"
        auto_public_ip: true
      register: influxdb

    - name: Create "{{ influxdb_lb_name }}" Listeners
      otc_listener:
        name: "{{ item.name }}"
        loadbalancer: "{{ influxdb.id }}"
        protocol: "{{ item.protocol }}"
        protocol_port: "{{ item.port }}"
      register: influxdb_listener_results
      loop:
        - {name: "listener_8086", protocol: "TCP", port: 8086}
        - {name: "listener_80", protocol: "TCP", port: 80}

    - name: Create "{{ haproxy_lb_name }}" Listeners
      otc_listener:
        name: "{{ item.name }}"
        loadbalancer: "{{ haproxy.id }}"
        protocol: "{{ item.protocol }}"
        protocol_port: "{{ item.port }}"
      register: haproxy_listener_results
      loop:
        - {name: "listener_443", protocol: "TCP", port: 443}
        - {name: "listener_80", protocol: "TCP", port: 80}
        
    - set_fact:
        influxdb_listeners: "{{ listeners| default({}) | combine({ item.item.name: item.id }) }}"
      with_items: "{{ influxdb_listener_results.results }}"

    - set_fact:
        haproxy_listeners: "{{ listeners| default({}) | combine({ item.item.name: item.id }) }}"
      with_items: "{{ haproxy_listener_results.results }}"
    
    - name: Create "{{ influxdb_lb_name }}" pools
      otc_pool:
        name: "{{ item.name }}"
        listener: "{{ item.listener }}"
        description: "{{ item.descr }}"
        protocol: "{{ item.protocol }}"
        lb_algorithm: "{{ item.algo }}"
        session_persistence:
          type: SOURCE_IP
      loop:
        - {name: "pool_8086", listener: "{{ influxdb_listeners.listener_8086 }}",
           descr: "8086 Pool", protocol: "TCP", algo: "SOURCE_IP"}
        - {name: "pool_80", listener: "{{ influxdb_listeners.listener_80 }}",
           descr: "80 Pool", protocol: "TCP", algo: "SOURCE_IP"}
      register:
        influxdb_pool_results

    - set_fact:
        influxdb_pools: "{{ pools| default({}) | combine({ item.item.name: item.id }) }}"
      with_items: "{{ influxdb_pool_results.results }}"

    - name: Find InfluxDB data
      os_server_facts:
        server: "{{ influxdb_host_server_fqdn }}"
      register: influx_server    
   
    - name: Register 8086 in the LB
      otc_member:
        pool: "{{ influxdb_pools.pool_8086 }}"
        address: "{{ influx_server.ansible_facts.openstack_servers[0].private_v4 }}"
        subnet_id: "{{ subnet_id }}"
        protocol_port: 8086
    
    - name: Register 80 in the LB
      otc_member:
        pool: "{{ influxdb_pools.pool_80 }}"
        address: "{{ influx_server.ansible_facts.openstack_servers[0].private_v4 }}"
        subnet_id: "{{ subnet_id }}"
        protocol_port: 80
