---
# tasks file for roles/executor


- name: Write telegraf systemd unit file
  become: true
  template:
    dest: "{{ telegraf_systemd_unit_path }}"
    src: telegraf-service.service

- name: Make sure Telegraf Conf dir exists
  become: true
  file:
    path: "/etc/telegraf"
    state: directory
    recurse: yes

- name: Write SSL Cert
  become: true
  copy:
    content: "{{ item.content }}"
    dest: "{{ ( '/etc/telegraf/' + item.name ) }}"
    mode: "{{ item.mode }}"
  loop:
    - {content: "{{telegraf_ssl_cert_content}}",
       name: "{{telegraf_ssl_cert_name}}",
       mode: "0644"}
    - {content: "{{telegraf_ssl_key_content}}",
       name: "{{telegraf_ssl_key_name}}",
       mode: "0600"}
    - {content: "{{telegraf_ssl_ca_cert_content}}",
       name: "{{telegraf_ssl_ca_cert_name}}",
       mode: "0644"}

- name: Write Telegraf Conf
  become: true
  template:
    src: "telegraf.conf"
    dest: "/etc/telegraf/telegraf.conf"

- name: Write Telegraf Env file
  become: true
  template:
    src: "env"
    dest: "/etc/telegraf/env"

- name: Start telegraf
  become: true
  systemd:
    name: "{{ telegraf_systemd_service_name }}"
    enabled: true
    state: "started"
    daemon_reload: true


